### ISSUE TITLE
Remove extra error line

### ISSUE THREAD

**Issue by jlandfried** [LastCallMedia/terminus-safe-deploy#3]
Extra error line should be removed: https://github.com/LastCallMedia/terminus-safe-deploy/blob/main/src/Slack.php#L51

@andy-lcm has context for this.

The fix can be submitted as a PR to this repo

**Comment by andyinman** [comment]
Done: https://github.com/LastCallMedia/terminus-safe-deploy/pull/4

**Comment by jlandfried** [comment]
Fixed in #4
